### ISSUE TITLE
update openocd to support stm32g0xx and stm32g4 devices

### ISSUE THREAD

**Issue by FRASTM** [zephyrproject-rtos/openocd#24]
update the openocd to include the support of stm32g0 and stm32g4 targets
on latest master which now includes the commit [Flash driver for STM32G0xx and STM32G4xx](http://openocd.zylin.com/#/c/4807/)

**Comment by FRASTM** [comment]
This would also include the PR https://github.com/zephyrproject-rtos/openocd/pull/11

**Comment by erwango** [comment]
@galak

**Comment by FRASTM** [comment]
no more relevant
