### ISSUE TITLE
ARM registers are incorrectly determined

### ISSUE THREAD

**Issue by dgloeck** [zephyrproject-rtos/openocd#4]
src/rtos/Zephyr.c uses rtos_standard_Cortex_M4F_FPU_stacking to read the 17 registers. But in Zephyr only 8 of them are on the stack. The other 9 are inside the _callee_saved structure where the stack pointer is taken from. With the current code r13 is offset by a constant and the values for r0-r3,r12,r14,r15 end up in r4-r11.

**Comment by galak** [comment]
> src/rtos/Zephyr.c uses rtos_standard_Cortex_M4F_FPU_stacking to read the 17 registers. But in Zephyr only 8 of them are on the stack. The other 9 are inside the _callee_saved structure where the stack pointer is taken from. With the current code r13 is offset by a constant and the values for r0-r3,r12,r14,r15 end up in r4-r11.

Thanks for catching this, do you have any ability to try and work on a fix?

**Comment by dgloeck** [comment]
@galak, I'm ready to make a pull request, but there is no suitable branch for merging into. The "master" branch is the unmodified upstream tree, the "zephyr" branch is based on an ancient version of OpenOCD, and the other branches appear to be snapshots as they have a date in their names.

**Comment by galak** [comment]
Go ahead and make the PR agains the zephyr-20190130 branch.  That's the most recent branch that we are using for the 0.10 sdk.

**Comment by galak** [comment]
Fixed by PR #5
