### ISSUE TITLE
open-ocd zephyr rtos awarness

### ISSUE THREAD

**Issue by manoj153** [zephyrproject-rtos/openocd#42]
```
The following RTOS values are supported by OpenOCD: eCos ThreadX FreeRTOS ChibiOS embKernel mqx uCOS-III auto
```
I am using cortex-debug extension but under the hood, open OCD pointed to openocd package bundled from v0.12.0 zephyr SDK, the question is do we have RTOS support?

**Comment by galak** [comment]
The OpenOCD in the SDK has Zephyr RTOS awareness support.

**Comment by manoj153** [comment]
Noted with thanks, as such, it's something to be done on config of my cortex-debug
