### ISSUE TITLE
Zephyr support does not work with ST-LINK

### ISSUE THREAD

**Issue by jonasn-ge** [zephyrproject-rtos/openocd#7]
When debugging an STM32 chip using ST-LINKv2 (for example Nucleo and Discovery boards) the target is set to "hla_target". That doesn't match the "cortex_m" that Zephyr.c is looking for, and the RTOS support doesn't work.
Several other RTOS integrations (FreeRTOS, ChibiOS) simply assume that hla_target means that they are talking to a cortex_m.

**Comment by galak** [comment]
@dgloeck do you think this issue is addressed by your PR?

**Comment by dgloeck** [comment]
@galak, no, this issue is not fixed by my PR, but it is easy to fix by duplicating the entry in the `Zephyr_params_list` array and setting `target_name` to `"hla_target"`.

Some background: hla_target is a special target where some of the low level JTAG sequences are implemented inside the JTAG adapter. Right now all JTAG adapters that implement the hla interface are for ARM cpus.

**Comment by galak** [comment]
> @galak, no, this issue is not fixed by my PR, but it is easy to fix by duplicating the entry in the `Zephyr_params_list` array and setting `target_name` to `"hla_target"`.
> 
> Some background: hla_target is a special target where some of the low level JTAG sequences are implemented inside the JTAG adapter. Right now all JTAG adapters that implement the hla interface are for ARM cpus.

can you add a commit to your PR for that?

**Comment by jonasn-ge** [comment]
I can confirm that @dgloeck's pull-request #5 works on my Nucleo board, if I add an entry for hla_target in Zephyr_params_list. I can then see all tasks' stacks.

**Comment by dgloeck** [comment]
@galak, done. I took a slightly different approach that will still work when hla_target starts supporting other architectures.

**Comment by jonasn-ge** [comment]
Works after pull-request #5 was merged, tested on Nucleo-f429. Thanks!
