### ISSUE TITLE
Upstream Zephyr RTOS awareness support

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/openocd#8]
This is just to track the effort to get the Zephyr RTOS support in upstream openocd.

**Comment by galak** [comment]
We had an enhancement request here for this:

https://github.com/zephyrproject-rtos/zephyr/issues/2933

**Comment by galak** [comment]
Here's the gerrit request in openocd for this:

http://openocd.zylin.com/#/c/4988/4

**Comment by EvgeniiDidin** [comment]
With this commit: http://openocd.zylin.com/gitweb?p=openocd.git;a=commit;h=77b28ced14321fbedb9493729a377856bab28144
Zephyr RTOS now is supported in upstream OpenOCD project.
